apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: slack-target
spec:
 template:
  spec:
   containers:
    - image: docker.io/ailispaw/slack-target
      env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-token
              key: SLACK_TOKEN
        - name: SLACK_CHANNEL
          value: triggermesh-target
